### ISSUE TITLE
[Bug]: tester does not run `use database` after reconnect to mo-service

### ISSUE THREAD

**Issue by w-zr** [matrixorigin/mo-tester#115]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

MO-Tester will reconnect to MO-Service after connection lost.
However, it does not run `use database` or other sql to resume test environment, which may make following cases fail.

**Comment by aressu1985** [comment]
fixed
